<?php
return array(
	"host"=>"smtp.gmail.com",
	"port"=>25,
	"auth"=>false,
	"user"=>"***",
	"password"=>"*****",
	"protocol"=>"smtp",
	"CharSet"=>"utf-8",
	"ns"=>"mail",
	"from"=>[
			"address"=>"*****",
			"name"=>"me"
			],
	"SMTPOptions"=>[
			"ssl"=>[
					"verify_peer"=>true,
					"verify_depth"=>3,
					"allow_self_signed"=>true,
					"peer_name"=>"smtp.example.com",
					"cafile"=>"/etc/ssl/ca_cert.pem"
					]
			]
	);